addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.3")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.0")
addSbtPlugin("io.shiftleft" % "sbt-ci-release-early" % "2.0.48")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.3.0")
addSbtPlugin("it.nicolasfarabegoli" % "sbt-conventional-commits" % "2.3.0")
