addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.11.1")
addSbtPlugin("io.shiftleft" % "sbt-ci-release-early" % "2.0.45")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.1.5")
addSbtPlugin("it.nicolasfarabegoli" % "sbt-conventional-commits" % "2.3.0")
